{
 "title": "Response Times",
 "description": "Dashboard for API response time visualisations\n",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Home Response Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests by endpoint",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (home_response_time_count) by (endpoint)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Response Time Heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum by (le) (rate(home_response_time_bucket[30s]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "# Unsuccessful and Successful requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by (statusCode) (rate(home_response_time_count{statusCode=~\"2..\"}[1h]))\n",
       "legendFormat": "Successful"
      },
      {
       "expr": "sum by (statusCode) (\n  rate(home_response_time_count{statusCode=~\"4..\"}[1h])\n) + ignoring(statusCode) group_left sum by (statusCode) (\n  rate(home_response_time_count{statusCode=~\"5..\"}[1h])\n)",
       "legendFormat": "Unsuccessful"
      }
     ]
    },
    {
     "title": "# requests by status codes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum by (statusCode)(home_response_time_count)",
       "legendFormat": "{{statusCode}}"
      }
     ]
    },
    {
     "title": "Average request response time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(home_response_time_sum[30s]))/sum(rate(home_response_time_count[30s]))",
       "legendFormat": "average response time"
      }
     ]
    }
   ]
  }
 ]
}